name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    # env:
    #   REPO: eu.gcr.io/breakingbad-w-kbit
    steps:
      # Checkout code (to get helm chart)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      # Set version and push tag
      - name: Set version
        id: version_bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "main"
      

      # Setup GCP
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
          export_default_credentials: true

  deploy_GKE:
    runs-on: 'ubuntu-latest'
    needs: [build]
    steps:
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials  ${{ secrets.GKE_PROJECT_ID }}-gke --zone europe-west1-c --project ${{ secrets.GKE_PROJECT_ID }}
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Deploy application
        run: kubectl apply -k ./
